name: Run Docker Tests

on:
  workflow_call:

jobs:
  run-docker-tests:
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: ./.uv-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run docker tests
        run: just docker-test