name: Run Local Tests

on:
  workflow_call:

jobs:
  run-local-tests:
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: ./.uv-cache
    strategy:
      fail-fast: false
      matrix:
        test_target: [unit-test, sqlt-test, intg-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run local tests
        env:
          USE_SQLITE: "true"
        run: just ${{ matrix.test_target }}